# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 7.4
  #- 8.0

before_script:
  - composer install --no-interaction

# Script to run tests
script: ./vendor/bin/phpunit

